### ISSUE TITLE
Products page: Product categories display should be based from the category orders at the backend.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Style-Lite#29]
![image](https://cloud.githubusercontent.com/assets/11186304/7040051/94910a46-ddfc-11e4-877f-3818d4c31b5e.png)

**Comment by maluzynel** [comment]
![image](https://cloud.githubusercontent.com/assets/11186304/7150529/c012935e-e34e-11e4-92ea-52b9fd6b4b1a.png)

**Comment by maluzynel** [comment]
Product categories are now showing up in the Products page.

**Comment by genesiscebudigital** [comment]
what do you mean?
