### ISSUE TITLE
Product single page: Featured image dimension size should match up to the design specs.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Style-Lite#48]
![image](https://cloud.githubusercontent.com/assets/11186304/7041973/aec461e2-de10-11e4-832e-1663ae64b642.png)

**Comment by maluzynel** [comment]
Not yet fixed

![image](https://cloud.githubusercontent.com/assets/11186304/7150576/480c835a-e34f-11e4-8d69-8f14bab4ee18.png)

**Comment by genesiscebudigital** [comment]
if the image is lower than the wordpress image size . , it will not crop . , try to upload larger image

**Comment by maluzynel** [comment]
This is flag as fixed related to the first issue.
