### ISSUE TITLE
Stockist listing page: Inconsistent dimension size of stockist items.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Style-Lite#59]
![image](https://cloud.githubusercontent.com/assets/11186304/7042947/2bc43e68-de18-11e4-8ba5-4dee6dd57989.png)

**Comment by genesiscebudigital** [comment]
if I don't crop the image in https://github.com/titan-cebu/Style-Lite/issues/90 . , the demension is Inconsistent

**Comment by maluzynel** [comment]
Featured image should be resized according to its required dimension size height/width.

![image](https://cloud.githubusercontent.com/assets/11186304/7150752/d9d8fbae-e351-11e4-964e-c4cd26f654d8.png)
